# .github/docker-compose.yml

networks:
  autoshow-network:
    name: autoshow-network

services:
  autoshow-postgres:
    build:
      # The context is "..", meaning "go up one directory from .github to the project root"
      context: ..
      # Then the Dockerfile is in .github/postgres-pgvector.Dockerfile 
      # (relative to the project root)
      dockerfile: .github/postgres-pgvector.Dockerfile
    container_name: autoshow-postgres
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-mypass}
      POSTGRES_DB: ${PGDATABASE:-mydatabase}
    ports:
      - "5432:5432"
    networks:
      - autoshow-network

  autoshow-service:
    build:
      context: ..
      dockerfile: .github/Dockerfile
    container_name: autoshow-service
    environment:
      PGHOST: autoshow-postgres
      PGUSER: ${PGUSER:-postgres}
      PGPASSWORD: ${PGPASSWORD:-mypass}
      PGDATABASE: ${PGDATABASE:-mydatabase}
    depends_on:
      - autoshow-postgres
    ports:
      - "3000:3000"
    networks:
      - autoshow-network
    volumes:
      - ./content:/usr/src/app/content
    command: "serve"