# .github/docker-compose.yml

networks:
  autoshow-network:
    name: autoshow-network

services:
  autoshow-postgres:
    build:
      context: ..
      dockerfile: .github/postgres-pgvector.Dockerfile
    container_name: autoshow-postgres
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-mypass}
      POSTGRES_DB: ${PGDATABASE:-mydatabase}
    ports:
      - "5432:5432"
    networks:
      - autoshow-network

  autoshow-service:
    build:
      context: ..
      dockerfile: .github/Dockerfile
    container_name: autoshow-service
    environment:
      PGHOST: autoshow-postgres
      PGPORT: 5432
      PGUSER: ${PGUSER:-postgres}
      PGPASSWORD: ${PGPASSWORD:-mypass}
      PGDATABASE: ${PGDATABASE:-mydatabase}
      DATABASE_URL: postgres://${PGUSER:-postgres}:${PGPASSWORD:-mypass}@autoshow-postgres:5432/${PGDATABASE:-mydatabase}

      # Or you can directly reference your .env (if it has the correct Docker host), but typically a direct override is more reliable:
      # DATABASE_URL: ${DATABASE_URL:-postgres://${PGUSER:-postgres}:${PGPASSWORD:-mypass}@autoshow-postgres:5432/${PGDATABASE:-mydatabase}}
    depends_on:
      - autoshow-postgres
    ports:
      - "3000:3000"
    networks:
      - autoshow-network
    volumes:
      - ./content:/usr/src/app/content
    command: "serve"