# .github/docker-compose.yml

networks:
  autoshow-network:
    name: autoshow-network

services:
  autoshow-postgres:
    build:
      context: ..
      dockerfile: .github/postgres-pgvector.Dockerfile
    container_name: autoshow-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - autoshow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 2s
      retries: 20

  autoshow-service:
    build:
      context: ..
      dockerfile: .github/Dockerfile
    container_name: autoshow-service
    environment:
      PGHOST: autoshow-postgres
      PGPORT: 5432
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGDATABASE: mydatabase
      DATABASE_URL: postgres://myuser:mypassword@autoshow-postgres:5432/mydatabase
    depends_on:
      autoshow-postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - autoshow-network
    volumes:
      - ../content:/usr/src/app/content