# docker-compose.yml

services:
  autoshow:
    # Use the parent directory (..) as the Docker build context
    build:
      context: ..
      dockerfile: .github/Dockerfile
    # Mount directories/files from host to container
    volumes:
      - ../content:/usr/src/app/content
      - ../.env:/usr/src/app/.env
    stdin_open: true
    tty: true