# docker-compose.yml

services:
  autoshow:
    image: autoshow
    build:
      context: ..
      dockerfile: .github/Dockerfile
    command: ["serve"]
    volumes:
      - ../content:/usr/src/app/content
    ports:
      - "3000:3000"