# docker-compose.yml

services:
  autoshow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./content:/usr/src/app/content
      - ./.env:/usr/src/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - whisper
      - ollama
    environment:
      - OLLAMA_HOST=ollama
    networks:
      - autoshownet
  whisper:
    build:
      context: ./whisper.cpp
      dockerfile: Dockerfile
    volumes:
      - ./content:/app/content
      - ./whisper.cpp/models:/app/models
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    networks:
      - autoshownet
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - autoshownet
networks:
  autoshownet:
    driver: bridge
volumes:
  ollama: