# docker-compose.yml

services:
  # Main application service
  autoshow:
    # Build configuration for this service
    build:
      # Use the current directory as build context
      context: .
      # Use the Dockerfile in the root directory
      dockerfile: Dockerfile
    # Mount these directories/files from host to container
    volumes:
      # Share content directory between host and container
      - ./content:/usr/src/app/content
      # Mount environment variables file
      - ./.env:/usr/src/app/.env
    stdin_open: true
    tty: true