# docker-compose.yml

services:
  autoshow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./content:/usr/src/app/content
      - ./.env:/usr/src/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - whisper
      - ollama
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
  whisper:
    build:
      context: ./whisper.cpp
      dockerfile: Dockerfile
    volumes:
      - ./content:/app/content
      - ./whisper.cpp/models:/app/models
    command: tail -f /dev/null
    tty: true
    stdin_open: true
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5