# docker-compose.yml

services:
  autoshow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./content:/usr/src/app/content
      - ./.env:/usr/src/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - whisper
      # - llama
  whisper:
    build:
      context: ./whisper.cpp
      dockerfile: Dockerfile
    volumes:
      - ./content:/app/content
      - ./whisper.cpp/models:/app/models
    command: tail -f /dev/null
    tty: true
    stdin_open: true
  # llama:
  #   build:
  #     context: ./llama.cpp
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./content:/app/content
  #   command: tail -f /dev/null
  #   tty: true
  #   stdin_open: true
volumes:
  whisper:
  # llama: