// src/llms/fireworks.ts

import { env } from '../utils/node-utils.ts'
import { err } from '../utils/logging.ts'
import type { LLMResult } from '../../shared/types.ts'

export async function callFireworks(
  prompt: string,
  transcript: string,
  modelId: string
): Promise<LLMResult> {
  if (!env['FIREWORKS_API_KEY']) {
    throw new Error('Missing FIREWORKS_API_KEY environment variable.')
  }
  
  const combinedPrompt = `${prompt}\n${transcript}`
  const requestBody = {
    model: modelId,
    messages: [{ role: 'user', content: combinedPrompt }]
  }
  
  try {
    const res = await fetch('https://api.fireworks.ai/inference/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env['FIREWORKS_API_KEY']}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(requestBody)
    })
    
    if (!res.ok) {
      const errorText = await res.text()
      throw new Error(`Fireworks API error: ${res.status} ${res.statusText} - ${errorText}`)
    }
    
    const data = await res.json()
    const content = data.choices?.[0]?.message?.content
    
    if (!content) {
      throw new Error('No content generated by the Fireworks API.')
    }
    
    return {
      content,
      usage: {
        stopReason: data.choices?.[0]?.finish_reason ?? 'unknown',
        input: data.usage?.prompt_tokens,
        output: data.usage?.completion_tokens,
        total: data.usage?.total_tokens
      }
    }
  } catch (error) {
    err(`Error in callFireworks: ${(error as Error).message}`)
    throw error
  }
}