// src/llms/together.ts

import { env } from 'node:process'
import { LLM_SERVICES_CONFIG } from '../../shared/constants'
import { err, logLLMCost } from '../utils/logging'

/**
 * Type union of all `.value` fields for Together models in {@link LLM_SERVICES_CONFIG}.
 */
type TogetherModelValue = (typeof LLM_SERVICES_CONFIG.together.models)[number]['value']

/**
 * Calls the Together AI API and returns generated text.
 *
 * @param prompt - The prompt or instructions to process.
 * @param transcript - The transcript text to be appended to the prompt.
 * @param modelValue - The string key identifying which Together AI model to use (e.g. "meta-llama/Llama-3.2-3B-Instruct-Turbo").
 * @returns The generated text from Together AI.
 * @throws If the `TOGETHER_API_KEY` is missing or no valid response content is found.
 */
export async function callTogether(
  prompt: string,
  transcript: string,
  modelValue: TogetherModelValue
): Promise<string> {
  if (!env['TOGETHER_API_KEY']) {
    throw new Error('Missing TOGETHER_API_KEY environment variable.')
  }

  const combinedPrompt = `${prompt}\n${transcript}`
  const requestBody = {
    model: modelValue,
    max_tokens: 4000,
    messages: [{ role: 'user', content: combinedPrompt }]
  }

  try {
    const response = await fetch('https://api.together.xyz/v1/chat/completions', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        Authorization: `Bearer ${env['TOGETHER_API_KEY']}`
      },
      body: JSON.stringify(requestBody)
    })

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`Together AI API error: ${response.status} ${response.statusText} - ${errorText}`)
    }

    const data = await response.json()
    const content = data.choices?.[0]?.message?.content
    if (!content) {
      throw new Error('No content generated by the Together AI API.')
    }

    logLLMCost({
      modelName: modelValue,
      stopReason: data.choices?.[0]?.finish_reason ?? 'unknown',
      tokenUsage: {
        input: data.usage?.prompt_tokens,
        output: data.usage?.completion_tokens,
        total: data.usage?.total_tokens
      }
    })

    return content
  } catch (error) {
    err(`Error in callTogether: ${(error as Error).message}`)
    throw error
  }
}