// web/db/insert-show-note.ts

import { db, ShowNote } from 'astro:db'

/**
 * Insert a new row into the ShowNote table using Astro DB (Drizzle).
 *
 * @param showLink - The link to the show or audio/video file.
 * @param channel - The name of the channel or show.
 * @param channelURL - The URL of the channel or show.
 * @param title - The title of the show note.
 * @param description - A description of the show or content.
 * @param publishDate - The date the show was published.
 * @param coverImage - A URL to the cover image for the show.
 * @param frontmatter - The original frontmatter data from the processed file.
 * @param prompt - The prompt or instructions used prior to transcript.
 * @param transcript - The transcript of the show content.
 * @param llmOutput - The output generated by the language model (only if LLM was used).
 *
 * @returns A Promise that resolves once the row is inserted.
 */
export async function insertShowNote(
  showLink: string,
  channel: string,
  channelURL: string,
  title: string,
  description: string,
  publishDate: string,
  coverImage: string,
  frontmatter: string,
  prompt: string,
  transcript: string,
  llmOutput: string
): Promise<void> {
  await db.insert(ShowNote).values({
    showLink,
    channel,
    channelURL,
    title,
    description,
    publishDate,
    coverImage,
    frontmatter,
    prompt,
    transcript,
    llmOutput,
  })
}