// test/server/server-models.ts

import fs from 'node:fs/promises'
import path from 'node:path'
import { l, err } from '../../src/utils/logging'

const BASE_URL = 'http://localhost:3000'
const OUTPUT_DIR = 'content'

const {
  DEEPGRAM_API_KEY,
  ASSEMBLY_API_KEY,
  OPENAI_API_KEY,
  ANTHROPIC_API_KEY,
  GEMINI_API_KEY,
  DEEPSEEK_API_KEY,
  FIREWORKS_API_KEY,
  TOGETHER_API_KEY
} = process.env

type LLMProvider = 'chatgpt' | 'claude' | 'gemini' | 'deepseek' | 'fireworks' | 'together'

interface RequestData {
  type: 'file' | 'video'
  filePath?: string
  url?: string
  prompts?: string[]
  whisperModel?: string
  transcriptionService?: string
  speakerLabels?: boolean
  llm?: LLMProvider
  llmModel?: string
  openaiApiKey?: string | undefined
  anthropicApiKey?: string | undefined
  geminiApiKey?: string | undefined
  deepseekApiKey?: string | undefined
  deepgramApiKey?: string | undefined
  assemblyApiKey?: string | undefined
  togetherApiKey?: string | undefined
  fireworksApiKey?: string | undefined
}

interface Request {
  data: RequestData
  endpoint: string
  outputFiles: string[]
}

const requests: Request[] = [
  // Original seed request
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      llm: 'chatgpt',
      llmModel: 'gpt-4o-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['01-chatgpt-gpt-4o-mini.md'],
  },

  // -- DEEPGRAM (nova-2) --
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4.5-preview',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['02-deepgram-nova-2__chatgpt-gpt-4.5-preview.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['03-deepgram-nova-2__chatgpt-gpt-4o.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['04-deepgram-nova-2__chatgpt-gpt-4o-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'o1-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['05-deepgram-nova-2__chatgpt-o1-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-7-sonnet-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['06-deepgram-nova-2__claude-claude-3-7-sonnet-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-5-haiku-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['07-deepgram-nova-2__claude-claude-3-5-haiku-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-opus-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['08-deepgram-nova-2__claude-claude-3-opus-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-pro',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['09-deepgram-nova-2__gemini-gemini-1.5-pro.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash-8b',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['10-deepgram-nova-2__gemini-gemini-1.5-flash-8b.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['11-deepgram-nova-2__gemini-gemini-1.5-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash-lite',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['12-deepgram-nova-2__gemini-gemini-2.0-flash-lite.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['13-deepgram-nova-2__gemini-gemini-2.0-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-chat',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['14-deepgram-nova-2__deepseek-deepseek-chat.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-reasoner',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['15-deepgram-nova-2__deepseek-deepseek-reasoner.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['16-deepgram-nova-2__fireworks-llama-v3p1-405b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['17-deepgram-nova-2__fireworks-llama-v3p1-70b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-8b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['18-deepgram-nova-2__fireworks-llama-v3p1-8b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p2-3b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['19-deepgram-nova-2__fireworks-llama-v3p2-3b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/qwen2p5-72b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['20-deepgram-nova-2__fireworks-qwen2p5-72b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Llama-3.2-3B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['21-deepgram-nova-2__together-Llama-3.2-3B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['22-deepgram-nova-2__together-3.1-405B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['23-deepgram-nova-2__together-3.1-70B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['24-deepgram-nova-2__together-3.1-8B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-27b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['25-deepgram-nova-2__together-gemma-2-27b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-9b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['26-deepgram-nova-2__together-gemma-2-9b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['27-deepgram-nova-2__together-Qwen2.5-72B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'nova-2',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-7B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['28-deepgram-nova-2__together-Qwen2.5-7B-Instruct-Turbo.md'],
  },

  // -- DEEPGRAM (base) --
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4.5-preview',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['29-deepgram-base__chatgpt-gpt-4.5-preview.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['30-deepgram-base__chatgpt-gpt-4o.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['31-deepgram-base__chatgpt-gpt-4o-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'o1-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['32-deepgram-base__chatgpt-o1-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-7-sonnet-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['33-deepgram-base__claude-claude-3-7-sonnet-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-5-haiku-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['34-deepgram-base__claude-claude-3-5-haiku-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-opus-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['35-deepgram-base__claude-claude-3-opus-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-pro',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['36-deepgram-base__gemini-gemini-1.5-pro.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash-8b',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['37-deepgram-base__gemini-gemini-1.5-flash-8b.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['38-deepgram-base__gemini-gemini-1.5-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash-lite',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['39-deepgram-base__gemini-gemini-2.0-flash-lite.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['40-deepgram-base__gemini-gemini-2.0-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-chat',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['41-deepgram-base__deepseek-deepseek-chat.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-reasoner',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['42-deepgram-base__deepseek-deepseek-reasoner.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['43-deepgram-base__fireworks-llama-v3p1-405b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['44-deepgram-base__fireworks-llama-v3p1-70b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-8b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['45-deepgram-base__fireworks-llama-v3p1-8b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p2-3b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['46-deepgram-base__fireworks-llama-v3p2-3b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/qwen2p5-72b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['47-deepgram-base__fireworks-qwen2p5-72b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Llama-3.2-3B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['48-deepgram-base__together-Llama-3.2-3B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['49-deepgram-base__together-3.1-405B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['50-deepgram-base__together-3.1-70B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['51-deepgram-base__together-3.1-8B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-27b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['52-deepgram-base__together-gemma-2-27b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-9b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['53-deepgram-base__together-gemma-2-9b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['54-deepgram-base__together-Qwen2.5-72B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'base',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-7B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['55-deepgram-base__together-Qwen2.5-7B-Instruct-Turbo.md'],
  },

  // -- DEEPGRAM (enhanced) --
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4.5-preview',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['56-deepgram-enhanced__chatgpt-gpt-4.5-preview.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['57-deepgram-enhanced__chatgpt-gpt-4o.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['58-deepgram-enhanced__chatgpt-gpt-4o-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'chatgpt',
      llmModel: 'o1-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['59-deepgram-enhanced__chatgpt-o1-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-7-sonnet-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['60-deepgram-enhanced__claude-claude-3-7-sonnet-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-5-haiku-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['61-deepgram-enhanced__claude-claude-3-5-haiku-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-opus-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['62-deepgram-enhanced__claude-claude-3-opus-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-pro',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['63-deepgram-enhanced__gemini-gemini-1.5-pro.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash-8b',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['64-deepgram-enhanced__gemini-gemini-1.5-flash-8b.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['65-deepgram-enhanced__gemini-gemini-1.5-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash-lite',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['66-deepgram-enhanced__gemini-gemini-2.0-flash-lite.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['67-deepgram-enhanced__gemini-gemini-2.0-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-chat',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['68-deepgram-enhanced__deepseek-deepseek-chat.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-reasoner',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['69-deepgram-enhanced__deepseek-deepseek-reasoner.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['70-deepgram-enhanced__fireworks-llama-v3p1-405b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['71-deepgram-enhanced__fireworks-llama-v3p1-70b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-8b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['72-deepgram-enhanced__fireworks-llama-v3p1-8b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p2-3b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['73-deepgram-enhanced__fireworks-llama-v3p2-3b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/qwen2p5-72b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['74-deepgram-enhanced__fireworks-qwen2p5-72b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Llama-3.2-3B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['75-deepgram-enhanced__together-Llama-3.2-3B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['76-deepgram-enhanced__together-3.1-405B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['77-deepgram-enhanced__together-3.1-70B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['78-deepgram-enhanced__together-3.1-8B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-27b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['79-deepgram-enhanced__together-gemma-2-27b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-9b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['80-deepgram-enhanced__together-gemma-2-9b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['81-deepgram-enhanced__together-Qwen2.5-72B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'deepgram',
      whisperModel: 'enhanced',
      deepgramApiKey: DEEPGRAM_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-7B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['82-deepgram-enhanced__together-Qwen2.5-7B-Instruct-Turbo.md'],
  },

  // -- ASSEMBLY (best) --
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4.5-preview',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['83-assembly-best__chatgpt-gpt-4.5-preview.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['84-assembly-best__chatgpt-gpt-4o.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['85-assembly-best__chatgpt-gpt-4o-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'o1-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['86-assembly-best__chatgpt-o1-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-7-sonnet-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['87-assembly-best__claude-claude-3-7-sonnet-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-5-haiku-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['88-assembly-best__claude-claude-3-5-haiku-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-opus-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['89-assembly-best__claude-claude-3-opus-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-pro',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['90-assembly-best__gemini-gemini-1.5-pro.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash-8b',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['91-assembly-best__gemini-gemini-1.5-flash-8b.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['92-assembly-best__gemini-gemini-1.5-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash-lite',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['93-assembly-best__gemini-gemini-2.0-flash-lite.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['94-assembly-best__gemini-gemini-2.0-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-chat',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['95-assembly-best__deepseek-deepseek-chat.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-reasoner',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['96-assembly-best__deepseek-deepseek-reasoner.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['97-assembly-best__fireworks-llama-v3p1-405b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['98-assembly-best__fireworks-llama-v3p1-70b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-8b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['99-assembly-best__fireworks-llama-v3p1-8b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p2-3b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['100-assembly-best__fireworks-llama-v3p2-3b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/qwen2p5-72b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['101-assembly-best__fireworks-qwen2p5-72b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Llama-3.2-3B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['102-assembly-best__together-Llama-3.2-3B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['103-assembly-best__together-3.1-405B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['104-assembly-best__together-3.1-70B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['105-assembly-best__together-3.1-8B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-27b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['106-assembly-best__together-gemma-2-27b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-9b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['107-assembly-best__together-gemma-2-9b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['108-assembly-best__together-Qwen2.5-72B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'best',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-7B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['109-assembly-best__together-Qwen2.5-7B-Instruct-Turbo.md'],
  },

  // -- ASSEMBLY (nano) --
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4.5-preview',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['110-assembly-nano__chatgpt-gpt-4.5-preview.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['111-assembly-nano__chatgpt-gpt-4o.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'gpt-4o-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['112-assembly-nano__chatgpt-gpt-4o-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'chatgpt',
      llmModel: 'o1-mini',
      openaiApiKey: OPENAI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['113-assembly-nano__chatgpt-o1-mini.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-7-sonnet-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['114-assembly-nano__claude-claude-3-7-sonnet-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-5-haiku-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['115-assembly-nano__claude-claude-3-5-haiku-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'claude',
      llmModel: 'claude-3-opus-latest',
      anthropicApiKey: ANTHROPIC_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['116-assembly-nano__claude-claude-3-opus-latest.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-pro',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['117-assembly-nano__gemini-gemini-1.5-pro.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash-8b',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['118-assembly-nano__gemini-gemini-1.5-flash-8b.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-1.5-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['119-assembly-nano__gemini-gemini-1.5-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash-lite',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['120-assembly-nano__gemini-gemini-2.0-flash-lite.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'gemini',
      llmModel: 'gemini-2.0-flash',
      geminiApiKey: GEMINI_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['121-assembly-nano__gemini-gemini-2.0-flash.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-chat',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['122-assembly-nano__deepseek-deepseek-chat.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'deepseek',
      llmModel: 'deepseek-reasoner',
      deepseekApiKey: DEEPSEEK_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['123-assembly-nano__deepseek-deepseek-reasoner.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['124-assembly-nano__fireworks-llama-v3p1-405b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['125-assembly-nano__fireworks-llama-v3p1-70b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p1-8b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['126-assembly-nano__fireworks-llama-v3p1-8b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/llama-v3p2-3b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['127-assembly-nano__fireworks-llama-v3p2-3b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'fireworks',
      llmModel: 'accounts/fireworks/models/qwen2p5-72b-instruct',
      fireworksApiKey: FIREWORKS_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['128-assembly-nano__fireworks-qwen2p5-72b-instruct.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Llama-3.2-3B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['129-assembly-nano__together-Llama-3.2-3B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['130-assembly-nano__together-3.1-405B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['131-assembly-nano__together-3.1-70B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['132-assembly-nano__together-3.1-8B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-27b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['133-assembly-nano__together-gemma-2-27b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'google/gemma-2-9b-it',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['134-assembly-nano__together-gemma-2-9b-it.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['135-assembly-nano__together-Qwen2.5-72B-Instruct-Turbo.md'],
  },
  {
    data: {
      type: 'file',
      filePath: 'content/audio.mp3',
      transcriptionService: 'assembly',
      whisperModel: 'nano',
      assemblyApiKey: ASSEMBLY_API_KEY,
      llm: 'together',
      llmModel: 'Qwen/Qwen2.5-7B-Instruct-Turbo',
      togetherApiKey: TOGETHER_API_KEY,
    },
    endpoint: '/api/process',
    outputFiles: ['136-assembly-nano__together-Qwen2.5-7B-Instruct-Turbo.md'],
  },
]

const fetchRequest = async (request: Request, index: number): Promise<void> => {
  try {
    const filesBefore: string[] = await fs.readdir(OUTPUT_DIR)

    const response: Response = await fetch(`${BASE_URL}${request.endpoint}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request.data),
    })
    l(`\nRequest ${index + 1} response status:`, response.status)
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`)
    }

    const result: { message: string } = await response.json()
    l(`Request ${index + 1} result: ${result.message}`)

    await new Promise((resolve) => setTimeout(resolve, 1000))

    const filesAfter: string[] = await fs.readdir(OUTPUT_DIR)
    const newFiles: string[] = filesAfter.filter((f) => !filesBefore.includes(f))
    newFiles.sort()

    const outputFiles = request.outputFiles

    if (newFiles.length > 0) {
      for (let i = 0; i < Math.min(newFiles.length, outputFiles.length); i++) {
        const oldFilePath = path.join(OUTPUT_DIR, newFiles[i]!)
        const newFileName = outputFiles[i]!
        const newFilePath = path.join(OUTPUT_DIR, newFileName)
        await fs.rename(oldFilePath, newFilePath)
        l(`File renamed: ${oldFilePath} --> ${newFilePath}`)
      }
    } else {
      l('No new files to rename for this request.')
    }
  } catch (error) {
    err(`Error in request ${index + 1}:`, error)
  }
}

const runAllRequests = async (): Promise<void> => {
  for (const [i, request] of requests.entries()) {
    await fetchRequest(request, i)
  }
}

runAllRequests()